# Generated by Django 4.0.1 on 2022-04-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(to='core.Book'),
        ),
    ]
