# Generated by Django 4.0.1 on 2022-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
