# Generated by Django 4.0.1 on 2022-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Жанр')),
            ],
        ),
        migrations.DeleteModel(
            name='Reed',
        ),
    ]
